name: Sync Fork

on:
  schedule:
    - cron: '*/30 * * * *'

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: mdevoldere/DWWM_2005
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          owner: mdevoldere
          base: master
          head: master
